### ISSUE TITLE
Bug with Setting Requirements for Rag Clothes on Character Creation

### ISSUE THREAD

**Issue by BraniyaKz** [Deadheim-project/ItemRequiresSkillLevel#1]
The game really doesn't like it when reqs are set for rag clothing. It prevents you from creating a new character, and spews the log output full of errors. For example I was using:

```
- PrefabName: ArmorRagsChest
  Requirements:
  - Skill: Level
    Level: 1
    BlockCraft: true
    BlockEquip: true
    EpicMMO: true
    ExhibitionName:
  - Skill: Body
    Level: 1
    BlockCraft: false
    BlockEquip: true
    EpicMMO: true
    ExhibitionName:
```
